import type { ReactNode } from "react";

import type { Metadata } from "next";
import { Figtree } from "next/font/google";

import { cx } from "@/utilities/classname";

import "./globals.css";

type RootLayoutProps = Readonly<{
  children: ReactNode;
}>;

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

const figtree = Figtree({
  subsets: ["latin", "latin-ext"],
  variable: "--font-figtree",
});

const RootLayout = ({ children }: RootLayoutProps) => (
  <html className={cx("scroll-smooth", figtree.variable)} lang="en">
    <body className="antialiased">{children}</body>
  </html>
);

export default RootLayout;
